### ISSUE TITLE
The 'wavy' footer design requires refactoring

### ISSUE THREAD

**Issue by nitinpaul** [sawaliram/sawaliram#126]
Our footer has a 'wavy' component that is made with SVG, which sits on top of the footer. There are two versions of the wave, one with `#ffffff` background and another with `#f2f2f2`. The ideal solution will be to have an SVG with transparent background, but we added a quickfix by setting a background for the <body> instead. Because of this, on some pages like the View Answer, we get this grey strip right under the green 'page title bar'. 
![Screenshot 2019-12-13 at 12 11 14 PM](https://user-images.githubusercontent.com/6622733/70777169-0cd02b80-1da5-11ea-9abb-95bd7feca641.png)
Another issue with the SVG component of the footer is the appearance of a gap between the SVG and the footer content which shows up on some screens. I am not able to reproduce it on my MacAir 13 - 1440px, but it appears on the retina iMac. Because of this, a thin grey line appears between the wave and the footer body, which looks bad. 

The ideal solution would be a 're-usable' version of the wave, that can be used for not just the footer, but as section dividers in the websites main content. The original designs can be found in the #design channel of our Zulip group.

**Comment by PeterMorganGH** [comment]
Changing the `min-height` property of `footer.wavy-footer::before` to a whole number fixed the issue of the gap between the wave and the solid background color. In my testing I used `min-height: 33px;`.

**Comment by PeterMorganGH** [comment]
The issue of the wavy footer needing 2 different fill colors on certain pages is a tricky one. The easiest solution - which you should test to make sure it works through the site - would be to add `height: 100%;` to `.filter-sidebar` to prevent it from being as tall as the other content. Then you would only have 1 background color at the bottom of the main content before the footer.

**Comment by nitinpaul** [comment]
I couldn't test the `min-height` property fix, since I am not able to reproduce the bug. @badrihippo can you maybe give it a try? I will try to get my hands on a monitor and see if I can check it. 
@PeterMorganGH you're right, it can also be managed by managing the design, like you said. This might be a noob question, but does SVG support transparent fill colors? If it does, can't we simply edit the footer CSS?

**Comment by badrihippo** [comment]
Partial solution. Changing `min-height` to a fixed number of pixels rather than `vw` solves the "grey line" issue, but the wave ceases to be proportional. (The reason for using `vw` was so the dimensions of the wave remain the same regardless of screen size; `3.68vw` comes from the height:width ratio of the wave svg). @PeterMorganGH do you know any trick to keep the ratio constant (maybe having it "jump" at certain breakpoints)?

Investigating this issue further, it seems to be dependent on screen-size. If you resize the screen, it will recur at certain points; probably where the ratio doesn't quite match up. @nitinpaul you could try that next time you want to test it; maybe we should note down the ratios at which it occurs (not sure how to do that in Chromium?).

One potential solution could be to extend the size of the PNG or change the background colour of that region to match.

Also, this seems to be a Webkit-specific issue since it doesn't occur in Firefox regardless of screen size. We could look into the differences between how the two browsers render CSS and see if there's some solution there (such as a missed out `-webkit-` property which Chrome's engine needs or some other behavioural quirks).

**Comment by PeterMorganGH** [comment]
@badrihippo I'm not sure if it would solve the problem, but maybe look into using the [CSS calc() function](https://developer.mozilla.org/en-US/docs/Web/CSS/calc) to maintain the correct ratio. If you want, you can set specific heights at different breakpoints, but you might need to set many of them.
