### ISSUE TITLE
Feature to add and remove user fom groups is missing

### ISSUE THREAD

**Issue by nitinpaul** [sawaliram/sawaliram#144]
Admin users must be able to manage the user groups and view user details. This issue will be a part of an overhaul for the Manage Users page.

**Comment by badrihippo** [comment]
Do you mean the groups like "Expert", "Translator", etc? Because that feature seems to be already there:

![manage-users](https://user-images.githubusercontent.com/7288084/71964280-4a4c9b00-3223-11ea-8c70-3963740028be.png)

I can check/uncheck the boxes and say "save" to update the user roles; I verified just now that it works with Write Articles. Seems to have been implemented in e3dea31fb6a2721121dec5d24f606ea6294e4de2.

The only issue is with [line 146](https://github.com/sawaliram/sawaliram/blob/b4992a9b67038ccf3e9d897e1ffddb205e18f6a6/sawaliram_auth/views.py#L146), which hard-codes the list of user groups rather than pulling them from the database. If that can be changed, we should be good to go?
