### ISSUE TITLE
Create a date stamp for "Published date" and "Submitted on (date)" 

### ISSUE THREAD

**Issue by dchandrika-tifr** [sawaliram/sawaliram#241]
The system seems to have a "Created On" and records "Last updated" version but not when it was submitted and published. 

Can that information be explicitly visible? 
a) "Submitted on" (along with Submitted by) in Review Answers
b)  "Published on" (along with Approved by/Published by) in Submit answer page

This will help us also sort by "Submitted on" date. Right now, only way to locate a question is using Question ID. The date will help prioritize long pending submission (apart from sorting by just oldest-newest)

These changes could be best seen on the above pages and /admin/dashboard/answers.

**Comment by badrihippo** [comment]
"Created on" and "Updated on" are now visible in the admin interface (fixed in #243).

There's no need for an explicit "Submitted on" date, because we can use the "updated on" field (the last time a submission was updated is probably also the time it was submitted; if not then it was edited later in which case it should be prioritised anyway. In any case, this variable would be used only during the review process and never afterwards, so it's best not to add it unless absolutely necessary.

The remaining task is to add a "Published on" date so we know when the item actually went public (as opposed to when it was last updated, which could be after the publication date).

**Comment by badrihippo** [comment]
Does the "published on" date need to be editable in the admin interface, or is it fine to have it read-only (like for "created on" and "updated on")?

**Comment by badrihippo** [comment]
> Does the "published on" date need to be editable in the admin interface, or is it fine to have it read-only (like for "created on" and "updated on")?

Final decision: no
