### ISSUE TITLE
Specify maximum image size for articles and answers

### ISSUE THREAD

**Issue by jr-sawaliram** [sawaliram/sawaliram#415]
Large images slow down the editor. 200 KB maximum size should be mandated.

**Comment by abhiprojectz** [comment]
@badrihippo  can you suggest which is best way to implement this , that fits in long run ?

**Comment by jr-sawaliram** [comment]
@abhiprojectz what are the options?

**Comment by abhiprojectz** [comment]
that's what i am asking for.

**Comment by badrihippo** [comment]
I'm not sure how to do it in CKEditor. My recommendation has always been not to let the images be embedded as base64 at all; instead they should be uploaded as separate files and linked using `<img>` tags like everywhere else. This would avoid slowing down the editor and would also improve the page load time. Again, no idea how to do it in CKEditor but there must be an option for this in the docs somewhere.

**Comment by badrihippo** [comment]
> `<img>` would need admin intervention and a PR for every image upload.

Not true; see [here](https://docs.djangoproject.com/en/3.2/topics/http/file-uploads/). User-uploaded images are stored in an "uploads" directory which is different from the `staticfiles` directory and not part of the source code so there is no need for any git or admin intervention. We are already using the upload feature when a user uploads an XML file—no PRs or admin intervention there either.

In fact, there is even a [django-ckeditor](https://django-ckeditor.readthedocs.io/en/latest/) which eases the process of setting up image uploads in CKEditor with Django. @abhiprojectz maybe you can take a look at this and see how easy it is to implement.

**Comment by abhiprojectz** [comment]
@badrihippo   i think **django-ckeditor** is not for what we are looking for , because in our codebase we need to refactor a lot to make it work, also if we are looking for only image upload functionality, there can be extensible methods. we can extends our ckeditor (that we are using right now) and can customize it.

**How if we can go as follows:**
1. Extends or create custom image upload class (`UploadAdapter`) in ckeditor to make it work according to our needs.
2. Images will be uploaded in `media/` directory and articles images will lie under sub-dirs `article`  while answers images will lie in `answers` dir ?

is it okay or Any further suggestions may you give ?

**Comment by abhiprojectz** [comment]
Also , All pages and static files are not compressed or minified at present, so this is also a major reason of slowing down of the site.

a `compressor` should be setup to minify the html and static `css` or `js` files.

**Comment by badrihippo** [comment]
@abhiprojectz that sounds good. The compressor is also a good idea; it won't solve this particular problem but is a good idea to have in general. Maybe you can make an issue for it? (This could be your first issue!)

I don't have any other suggestions; uploading into the `media/` directory sounds about right. @jr-sawaliram at some point we should start taking backups of this folder in addition to the database backups (however they are happening), because user-uploaded files are not (and should not be) included in git. Again, a topic for a separate issue.

**Comment by jr-sawaliram** [comment]
Looks like the discussions in #41 and #145 are still relevant. Any take-aways from there?

**Comment by abhiprojectz** [comment]
@badrihippo  issue created [#428 ](https://github.com/sawaliram/sawaliram/issues/428).

**Comment by badrihippo** [comment]
#145 is not relevant in this case; it's more about the official assets (such as logos and homepage graphics) rather than user-uploaded ones.

#41 has some good suggestions. We should look into using `ImageField` rather than uploading directly, since it is specially designed for images. We can still go with @abhiprojectz' original suggestion of creating a custom `UploadAdapter`, but that adapter can use `ImageField` in the backend instead of a normal file field. Of course, we should ignore the final decision of sticking with base64 because in hindsight that was a bad idea.

On a related note, if we ever decide to change the editor (like how we switched from QuillJS to CKEditor) then we should look into one of the editors mentioned in #91 because they're cleaner than traditional HTML editors. The reason is they don't have too many options, so articles will end up with a consistent style which we can control. This is similar to the way websites like [Medium](https://medium.com) maintain a consistent style and brand by not giving too many options like font, etc. to the users. (These options are okay for a personal blog, but in a collaborative website or platform like this one they'd only end up making it look messy and inconsistent). Of course, this is only if we don't manage to find a good CKEditor integration, but I think the custom `UploadAdapter` idea will work so let's give that a shot first :slightly_smiling_face:
